#! env sh

which java > /dev/null
if [ $? -ne 0 ]; then
    echo "[homebrew:jpipe] Java not found"
    exit 1
fi

which dot > /dev/null
if [ $? -ne 0 ]; then
    echo "[homebrew:jpipe] Graphviz not found"
    exit 1
fi

echo java -jar @@PREFIX@@/jpipe.jar "$@"
