name: Release extension


on:
  push:
    tags:
      - "v*.*.*.EXT"

jobs:
  build:

    runs-on: macos-latest
    defaults:
       run:
         working-directory: ./vs-extension/

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: cd vs-extension
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./vs-extension/package-lock.json
    - run: npm install -g @vscode/vsce
    - run: npm install
    - run: vsce package
    
    - name: Publish
      run: vsce publish -p ${{ secrets.VS_MARKETPLACE_MGMT_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: jpipe-*.vsix