# workflow to produce the VS code extension

name: VS Code

on: 
  push: 
    paths:
      - 'langium/**'
  pull_request:
    paths:
      - 'langium/**'
  workflow_call:      # Allow the workflow to be called by othersinputs:
    inputs:
      compiler_available:
        required: false
        type: boolean
  workflow_dispatch:  # Can be triggered manually

env:
  NODEJS_VERSION: '21.2.0'
  JPIPE_WEB:  'https://github.com/ace-design/jpipe/releases/download/0.1.0/jpipe.jar' 
  FOLDER:         './langium'   # Source code location


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ${{env.FOLDER}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ###                                                                    ###
      # If compiler available, get from artefacts. If not, get stable from web #
      ###                                                                    ###

      - name: Embed latest stable version of the compiler
        if: inputs.compiler_available == false
        run: |
          wget -O ./jar/jpipe.jar ${{env.JPIPE_WEB}}
      
      - name: retrieve compiler from environment
        if: inputs.compiler_available == true
        uses: actions/download-artifact@v4
        with:
          name: jpipe.jar
          path: ./jar/jpipe.jar

      ###                          ###
      # End of conditional behaviour #
      ###                          ###

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{env.NODEJS_VERSION}}'

      - name: Install vsce to package code
        run: |
          npm install
          npm install -g @vscode/vsce
      
      - name: Package extension as VSIX artefact
        run: |
          vsce package -o jpipe-extension.vsix
      
      - name: Upload VSIX artefact
        uses: actions/upload-artifact@v4
        with:
          name: jpipe-extension.vsix
          path: langium/jpipe-extension.vsix
    