# workflow to produce the VS code extension

name: VS Code

on: 
  push: 
    paths:
      - 'langium/**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'langium/**'
  workflow_dispatch:  # Can be triggered manually

env:
  NODEJS_VERSION: '22.13.0'
  JPIPE_WEB:      'https://github.com/ace-design/jpipe/releases/download/0.1.0/jpipe.jar' 
  FOLDER:         './langium'   # Source code location


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ${{env.FOLDER}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Embed latest stable version of the compiler
        run: |
          wget -O ./jar/jpipe.jar ${{env.JPIPE_WEB}}
  
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{env.NODEJS_VERSION}}'

      - name: Install vsce to package code
        run: |
          npm install
          npm install -g @vscode/vsce
      
      - name: Package extension as VSIX artefact
        run: |
          vsce package -o jpipe-extension.vsix
      
      - name: Upload VSIX artefact
        uses: actions/upload-artifact@v4
        with:
          name: jpipe-extension.vsix
          path: langium/jpipe-extension.vsix
    
